# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_api_key: <%= ENV["STRIPE_API_KEY"] %>
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
  stripe_currency: <%= ENV["STRIPE_CURRENCY"] %>
  disqus_shortname: <%= ENV["DISQUS_SHORTNAME"] %>
  fablab_without_plans: <%= ENV["FABLAB_WITHOUT_PLANS"] %>
  default_host: <%= ENV["DEFAULT_HOST"] %>
  default_protocol: <%= ENV["DEFAULT_PROTOCOL"] %>
  time_zone: <%= ENV["TIME_ZONE"] %>
  week_starting_day: <%= ENV["WEEK_STARTING_DAY"] %>
  d3_date_format: <%= ENV["D3_DATE_FORMAT"].dump %>  # .dump is needed as the value may start by a '%', see https://github.com/tenderlove/psych/issues/75
  uib_date_format: <%= ENV["UIB_DATE_FORMAT"] %>
  excel_date_format: <%= ENV["EXCEL_DATE_FORMAT"]%>
  rails_locale: <%= ENV["RAILS_LOCALE"] %>
  moment_locale: <%= ENV["MOMENT_LOCALE"] %>
  summernote_locale: <%= ENV["SUMMERNOTE_LOCALE"] %>
  angular_locale: <%= ENV["ANGULAR_LOCALE"] %>
  messageformat_locale: <%= ENV["MESSAGEFORMAT_LOCALE"] %>
  fullcalendar_locale: <%= ENV["FULLCALENDAR_LOCALE"] %>
  elasticsearch_language_analyzer: <%= ENV["ELASTICSEARCH_LANGUAGE_ANALYZER"] %>
  openlab_app_secret: <%= ENV["OPENLAB_APP_SECRET"] %>
  openlab_app_id: <%= ENV["OPENLAB_APP_ID"] %>
  openlab_base_uri: <%= ENV["OPENLAB_BASE_URI"] %>
  navinum_api_login: <%= ENV["NAVINUM_API_LOGIN"] %>
  navinum_api_password: <%= ENV["NAVINUM_API_PASSWORD"] %>
  log_level: <%= ENV["LOG_LEVEL"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  elaticsearch_host: <%= ENV["ELASTICSEARCH_HOST"] %>
  max_image_size: <%= ENV["MAX_IMAGE_SIZE"] %>

test:
  secret_key_base: 83daf5e7b80d990f037407bab78dff9904aaf3c195a50f84fa8695a22287e707dfbd9524b403b1dcf116ae1d8c06844c3d7ed942564e5b46be6ae3ead93a9d30
  stripe_api_key: <%= ENV["STRIPE_API_KEY"] %>
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
  stripe_currency: usd
  disqus_shortname: fablab-sleede
  fablab_without_plans: false
  default_host: <%= ENV["DEFAULT_HOST"] %>
  default_protocol: <%= ENV["DEFAULT_PROTOCOL"] %>
  time_zone: Paris
  week_starting_day: monday
  d3_date_format: '%d/%m/%y'
  uib_date_format: dd/MM/yyyy
  excel_date_format: dd/mm/yyyy
  rails_locale: en
  moment_locale: en
  summernote_locale: en-US
  angular_locale: en-us
  messageformat_locale: en
  fullcalendar_locale: en
  elasticsearch_language_analyzer: french
  openlab_app_secret:
  openlab_app_id:
  openlab_base_uri:
  navinum_api_login:
  navinum_api_password:
  log_level: <%= ENV["LOG_LEVEL"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  elaticsearch_host: localhost
  max_image_size: <%= ENV["MAX_IMAGE_SIZE"] %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_api_key: <%= ENV["STRIPE_API_KEY"] %>
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
  stripe_currency: <%= ENV["STRIPE_CURRENCY"] %>
  disqus_shortname: <%= ENV["DISQUS_SHORTNAME"] %>
  fablab_without_plans: <%= ENV["FABLAB_WITHOUT_PLANS"] %>
  default_host: <%= ENV["DEFAULT_HOST"] %>
  default_protocol: <%= ENV["DEFAULT_PROTOCOL"] %>
  delivery_method: <%= ENV['DELIVERY_METHOD'] %>
  smtp_address: <%= ENV["SMTP_ADDRESS"] %>
  smtp_port: <%= ENV["SMTP_PORT"] %>
  smtp_user_name: <%= ENV["SMTP_USER_NAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
  time_zone: <%= ENV["TIME_ZONE"] %>
  week_starting_day: <%= ENV["WEEK_STARTING_DAY"] %>
  d3_date_format: <%= ENV["D3_DATE_FORMAT"].dump %>
  uib_date_format: <%= ENV["UIB_DATE_FORMAT"] %>
  excel_date_format: <%= ENV["EXCEL_DATE_FORMAT"]%>
  rails_locale: <%= ENV["RAILS_LOCALE"] %>
  moment_locale: <%= ENV["MOMENT_LOCALE"] %>
  summernote_locale: <%= ENV["SUMMERNOTE_LOCALE"] %>
  angular_locale: <%= ENV["ANGULAR_LOCALE"] %>
  messageformat_locale: <%= ENV["MESSAGEFORMAT_LOCALE"] %>
  fullcalendar_locale: <%= ENV["FULLCALENDAR_LOCALE"] %>
  elasticsearch_language_analyzer: <%= ENV["ELASTICSEARCH_LANGUAGE_ANALYZER"] %>
  openlab_app_secret: <%= ENV["OPENLAB_APP_SECRET"] %>
  openlab_app_id: <%= ENV["OPENLAB_APP_ID"] %>
  openlab_base_uri: <%= ENV["OPENLAB_BASE_URI"] %>
  navinum_api_login: <%= ENV["NAVINUM_API_LOGIN"] %>
  navinum_api_password: <%= ENV["NAVINUM_API_PASSWORD"] %>
  log_level: <%= ENV["LOG_LEVEL"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  elaticsearch_host: <%= ENV["ELASTICSEARCH_HOST"] %>
  max_image_size: <%= ENV["MAX_IMAGE_SIZE"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_api_key: <%= ENV["STRIPE_API_KEY"] %>
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
  stripe_currency: <%= ENV["STRIPE_CURRENCY"] %>
  disqus_shortname: <%= ENV["DISQUS_SHORTNAME"] %>
  fablab_without_plans: <%= ENV["FABLAB_WITHOUT_PLANS"] %>
  default_host: <%= ENV["DEFAULT_HOST"] %>
  default_protocol: <%= ENV["DEFAULT_PROTOCOL"] %>
  delivery_method: <%= ENV['DELIVERY_METHOD'] %>
  smtp_address: <%= ENV["SMTP_ADDRESS"] %>
  smtp_port: <%= ENV["SMTP_PORT"] %>
  smtp_user_name: <%= ENV["SMTP_USER_NAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
  time_zone: <%= ENV["TIME_ZONE"] %>
  week_starting_day: <%= ENV["WEEK_STARTING_DAY"] %>
  d3_date_format: <%= ENV["D3_DATE_FORMAT"].dump %>
  uib_date_format: <%= ENV["UIB_DATE_FORMAT"] %>
  excel_date_format: <%= ENV["EXCEL_DATE_FORMAT"]%>
  rails_locale: <%= ENV["RAILS_LOCALE"] %>
  moment_locale: <%= ENV["MOMENT_LOCALE"] %>
  summernote_locale: <%= ENV["SUMMERNOTE_LOCALE"] %>
  angular_locale: <%= ENV["ANGULAR_LOCALE"] %>
  messageformat_locale: <%= ENV["MESSAGEFORMAT_LOCALE"] %>
  fullcalendar_locale: <%= ENV["FULLCALENDAR_LOCALE"] %>
  elasticsearch_language_analyzer: <%= ENV["ELASTICSEARCH_LANGUAGE_ANALYZER"] %>
  openlab_app_secret: <%= ENV["OPENLAB_APP_SECRET"] %>
  openlab_app_id: <%= ENV["OPENLAB_APP_ID"] %>
  openlab_base_uri: <%= ENV["OPENLAB_BASE_URI"] %>
  google_analytics_id: <%= ENV["GA_ID"] %>
  navinum_api_login: <%= ENV["NAVINUM_API_LOGIN"] %>
  navinum_api_password: <%= ENV["NAVINUM_API_PASSWORD"] %>
  log_level: <%= ENV["LOG_LEVEL"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  elaticsearch_host: <%= ENV["ELASTICSEARCH_HOST"] %>
  max_image_size: <%= ENV["MAX_IMAGE_SIZE"] %>
