# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  default_host: <%= ENV["DEFAULT_HOST"] %>
  default_protocol: <%= ENV["DEFAULT_PROTOCOL"] %>
  smtp_address: <%= ENV["SMTP_ADDRESS"] %>
  smtp_port: <%= ENV["SMTP_PORT"] %>
  time_zone: <%= ENV["TIME_ZONE"] %>
  week_starting_day: <%= ENV["WEEK_STARTING_DAY"] %>
  d3_date_format: <%= ENV["D3_DATE_FORMAT"].dump %>  # .dump is needed as the value may start by a '%', see https://github.com/tenderlove/psych/issues/75
  uib_date_format: <%= ENV["UIB_DATE_FORMAT"] %>
  excel_date_format: <%= ENV["EXCEL_DATE_FORMAT"]%>
  rails_locale: <%= ENV["RAILS_LOCALE"] %>
  app_locale: <%= ENV["APP_LOCALE"] %>
  moment_locale: <%= ENV["MOMENT_LOCALE"] %>
  summernote_locale: <%= ENV["SUMMERNOTE_LOCALE"] %>
  angular_locale: <%= ENV["ANGULAR_LOCALE"] %>
  intl_locale: <%= ENV["INTL_LOCALE"] %>
  intl_currency: <%= ENV["INTL_CURRENCY"] %>
  fullcalendar_locale: <%= ENV["FULLCALENDAR_LOCALE"] %>
  postgresql_language_analyzer: <%= ENV.fetch("POSTGRESQL_LANGUAGE_ANALYZER", 'simple') %>
  openlab_base_uri: <%= ENV["OPENLAB_BASE_URI"] %>
  navinum_api_login: <%= ENV["NAVINUM_API_LOGIN"] %>
  navinum_api_password: <%= ENV["NAVINUM_API_PASSWORD"] %>
  elaticsearch_host: <%= ENV["ELASTICSEARCH_HOST"] %>
  max_image_size: <%= ENV["MAX_IMAGE_SIZE"] %>
  max_cao_size: <%= ENV["MAX_CAO_SIZE"] %>
  max_import_size: <%= ENV["MAX_IMPORT_SIZE"] %>
  disk_space_mb_alert: <%= ENV["DISK_SPACE_MB_ALERT"] %>
  adminsys_email: <%= ENV["ADMINSYS_EMAIL"] %>
  allow_insecure_http: <%= ENV.fetch("ALLOW_INSECURE_HTTP", false) %>
  locked_settings: <%= ENV.fetch("LOCKED_SETTINGS", 'uuid,origin').split(/,/) %>

test:
  secret_key_base: 83daf5e7b80d990f037407bab78dff9904aaf3c195a50f84fa8695a22287e707dfbd9524b403b1dcf116ae1d8c06844c3d7ed942564e5b46be6ae3ead93a9d30
  default_host: <%= ENV["DEFAULT_HOST"] %>
  default_protocol: <%= ENV["DEFAULT_PROTOCOL"] %>
  time_zone: Paris
  week_starting_day: monday
  d3_date_format: '%d/%m/%y'
  uib_date_format: dd/MM/yyyy
  excel_date_format: dd/mm/yyyy
  rails_locale: en
  app_locale: en
  moment_locale: en
  summernote_locale: en-US
  angular_locale: en-us
  intl_locale: en-US
  intl_currency: USD
  fullcalendar_locale: en
  postgresql_language_analyzer: french
  openlab_base_uri:
  navinum_api_login:
  navinum_api_password:
  elaticsearch_host: <%= ENV["ELASTICSEARCH_HOST"] %>
  max_image_size: <%= ENV["MAX_IMAGE_SIZE"] %>
  max_cao_size: <%= ENV["MAX_CAO_SIZE"] %>
  max_import_size: <%= ENV["MAX_IMPORT_SIZE"] %>
  disk_space_mb_alert: <%= ENV["DISK_SPACE_MB_ALERT"] %>
  adminsys_email: <%= ENV["ADMINSYS_EMAIL"] %>
  allow_insecure_http: <%= ENV.fetch("ALLOW_INSECURE_HTTP", false) %>
  locked_settings: <%= ENV.fetch("LOCKED_SETTINGS", 'uuid,origin').split(/,/) %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  default_host: <%= ENV["DEFAULT_HOST"] %>
  default_protocol: <%= ENV["DEFAULT_PROTOCOL"] %>
  delivery_method: <%= ENV['DELIVERY_METHOD'] %>
  smtp_address: <%= ENV["SMTP_ADDRESS"] %>
  smtp_port: <%= ENV["SMTP_PORT"] %>
  smtp_user_name: <%= ENV["SMTP_USER_NAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
  smtp_authentication: <%= ENV["SMTP_AUTHENTICATION"] %>
  smtp_enable_starttls_auto: <%= ENV["SMTP_ENABLE_STARTTLS_AUTO"] %>
  smtp_openssl_verify_mode: <%= ENV["SMTP_OPENSSL_VERIFY_MODE"] %>
  time_zone: <%= ENV["TIME_ZONE"] %>
  week_starting_day: <%= ENV["WEEK_STARTING_DAY"] %>
  d3_date_format: <%= ENV["D3_DATE_FORMAT"].dump %>
  uib_date_format: <%= ENV["UIB_DATE_FORMAT"] %>
  excel_date_format: <%= ENV["EXCEL_DATE_FORMAT"]%>
  rails_locale: <%= ENV["RAILS_LOCALE"] %>
  app_locale: <%= ENV["APP_LOCALE"] %>
  moment_locale: <%= ENV["MOMENT_LOCALE"] %>
  summernote_locale: <%= ENV["SUMMERNOTE_LOCALE"] %>
  angular_locale: <%= ENV["ANGULAR_LOCALE"] %>
  intl_locale: <%= ENV["INTL_LOCALE"] %>
  intl_currency: <%= ENV["INTL_CURRENCY"] %>
  fullcalendar_locale: <%= ENV["FULLCALENDAR_LOCALE"] %>
  postgresql_language_analyzer: <%= ENV.fetch("POSTGRESQL_LANGUAGE_ANALYZER", 'simple') %>
  openlab_base_uri: <%= ENV["OPENLAB_BASE_URI"] %>
  navinum_api_login: <%= ENV["NAVINUM_API_LOGIN"] %>
  navinum_api_password: <%= ENV["NAVINUM_API_PASSWORD"] %>
  elaticsearch_host: <%= ENV["ELASTICSEARCH_HOST"] %>
  max_image_size: <%= ENV["MAX_IMAGE_SIZE"] %>
  max_cao_size: <%= ENV["MAX_CAO_SIZE"] %>
  max_import_size: <%= ENV["MAX_IMPORT_SIZE"] %>
  disk_space_mb_alert: <%= ENV["DISK_SPACE_MB_ALERT"] %>
  adminsys_email: <%= ENV["ADMINSYS_EMAIL"] %>
  enable_in_context_translation: <%= ENV["ENABLE_IN_CONTEXT_TRANSLATION"] %>
  allow_insecure_http: <%= ENV.fetch("ALLOW_INSECURE_HTTP", false) %>
  locked_settings: <%= ENV.fetch("LOCKED_SETTINGS", 'uuid,origin').split(/,/) %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  default_host: <%= ENV["DEFAULT_HOST"] %>
  default_protocol: <%= ENV["DEFAULT_PROTOCOL"] %>
  delivery_method: <%= ENV['DELIVERY_METHOD'] %>
  smtp_address: <%= ENV["SMTP_ADDRESS"] %>
  smtp_port: <%= ENV["SMTP_PORT"] %>
  smtp_user_name: <%= ENV["SMTP_USER_NAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
  time_zone: <%= ENV["TIME_ZONE"] %>
  smtp_authentication: <%= ENV["SMTP_AUTHENTICATION"] %>
  smtp_enable_starttls_auto: <%= ENV["SMTP_ENABLE_STARTTLS_AUTO"] %>
  smtp_openssl_verify_mode: <%= ENV["SMTP_OPENSSL_VERIFY_MODE"] %>
  week_starting_day: <%= ENV["WEEK_STARTING_DAY"] %>
  d3_date_format: <%= ENV["D3_DATE_FORMAT"].dump %>
  uib_date_format: <%= ENV["UIB_DATE_FORMAT"] %>
  excel_date_format: <%= ENV["EXCEL_DATE_FORMAT"]%>
  rails_locale: <%= ENV["RAILS_LOCALE"] %>
  app_locale: <%= ENV["APP_LOCALE"] %>
  moment_locale: <%= ENV["MOMENT_LOCALE"] %>
  summernote_locale: <%= ENV["SUMMERNOTE_LOCALE"] %>
  angular_locale: <%= ENV["ANGULAR_LOCALE"] %>
  intl_locale: <%= ENV["INTL_LOCALE"] %>
  intl_currency: <%= ENV["INTL_CURRENCY"] %>
  fullcalendar_locale: <%= ENV["FULLCALENDAR_LOCALE"] %>
  postgresql_language_analyzer: <%= ENV.fetch("POSTGRESQL_LANGUAGE_ANALYZER", 'simple') %>
  openlab_base_uri: <%= ENV["OPENLAB_BASE_URI"] %>
  navinum_api_login: <%= ENV["NAVINUM_API_LOGIN"] %>
  navinum_api_password: <%= ENV["NAVINUM_API_PASSWORD"] %>
  elaticsearch_host: <%= ENV["ELASTICSEARCH_HOST"] %>
  max_image_size: <%= ENV["MAX_IMAGE_SIZE"] %>
  max_cao_size: <%= ENV["MAX_CAO_SIZE"] %>
  max_import_size: <%= ENV["MAX_IMPORT_SIZE"] %>
  disk_space_mb_alert: <%= ENV["DISK_SPACE_MB_ALERT"] %>
  adminsys_email: <%= ENV["ADMINSYS_EMAIL"] %>
  allow_insecure_http: <%= ENV.fetch("ALLOW_INSECURE_HTTP", false) %>
  locked_settings: <%= ENV.fetch("LOCKED_SETTINGS", 'uuid,origin').split(/,/) %>
